SHOW server_version;

DO $$ BEGIN  
  IF EXISTS (SELECT FROM pg_database WHERE datname = 'BooksManager') THEN
      RAISE NOTICE 'Database already exists';  -- optional
   ELSE
      
   END IF;
END$$;

CREATE DATABASE BooksManager;

DO $$ BEGIN     
    IF TRUE <> (SELECT EXISTS(SELECT 1 FROM information_schema.schemata WHERE schema_name = 'books') ) THEN            
      CREATE SCHEMA books;
    END IF;
END$$;

SET SCHEMA 'books';

CREATE TABLE IF NOT EXISTS BookGenres (
    id    int         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar(40) NOT NULL,
    UNIQUE(name)    
);

CREATE TABLE IF NOT EXISTS Books (
    id    int          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar(150) NOT NULL        
);

CREATE TABLE IF NOT EXISTS BookGenres_Items(
    book_id        int REFERENCES Books      ON DELETE RESTRICT,
    book_genres_id int REFERENCES BookGenres ON DELETE CASCADE,
    PRIMARY KEY(book_id, book_genres_id)
);




--SELECT * FROM BookGenres;
--SELECT * FROM Books;
--SELECT * FROM BookGenres_Items;